spring.application.name=gestion-entreprise
# URL de la base H2 (en mémoire)
spring.datasource.url=jdbc:h2:mem:entreprise

# Driver H2
spring.datasource.driverClassName=org.h2.Driver

# Identifiants
spring.datasource.username=sa
spring.datasource.password=

# Dialecte JPA
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Création automatique des tables
spring.jpa.hibernate.ddl-auto=update

# Affichage des requêtes SQL
spring.jpa.show-sql=true

# Console H2 activée
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console